# Generated by Django 4.2 on 2025-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_studentdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
