# Generated by Django 4.2 on 2025-07-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_alter_studentdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credit',
            new_name='marks',
        ),
    ]
